In [1]:
import numpy as np

In [3]:
radius =2
kernel = np.zeros((2*radius+1, 2*radius+1))
y,x = np.ogrid[-radius:radius+1, -radius:radius+1]
mask = x**2 + y**2 <= radius**2
kernel[mask] = 1
kernel

array([[0., 0., 1., 0., 0.],
       [0., 1., 1., 1., 0.],
       [1., 1., 1., 1., 1.],
       [0., 1., 1., 1., 0.],
       [0., 0., 1., 0., 0.]])

In [5]:
a = np.zeros((5,5))
a[1,1] = 10
a[0,4] = 20
a

array([[ 0.,  0.,  0.,  0., 20.],
       [ 0., 10.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

In [7]:
a[kernel.astype(bool)]

array([ 0., 10.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.])

In [20]:
v = []
for _ in range(100):
    v += [np.random.binomial(1, 0.1)]
    if v[-1]:
        print('cioa')
len([x for x in v if x == 1])

cioa
cioa
cioa
cioa
cioa
cioa
cioa


7